services:
  minecraft:
    build: 
      context: .
      args:
        RCON_PORT: ${RCON_PORT}
        RCON_PWD: ${RCON_PWD}
        MOTD: ${MOTD}
        ENABLE_WHITELIST: ${ENABLE_WHITELIST:-true}
        MEMORY: ${MEMORY:-6G}
        JAVA_ARGS: ${JAVA_ARGS}
    container_name: ${PACK_NAME}
    restart: unless-stopped
    ports:
      - "${SERVER_PORT}:25565"
    expose:
      - "${RCON_PORT}"
    volumes:
      - "${SERVER_DIR:-./server}:/opt/mcserver"
